#To run this play book use below command
#ansible-playbook userAdd.yml --extra-vars "username=raja userpassword=raja345"
---
- name: Add user
  hosts: webserver
  become: true
  become_user: root
  tasks:
    - name: change given password to encrypted
      local_action: command python -c 'import crypt; print crypt.crypt("{{ userpassword }}", "$1$SomeSalt$")'
      register: encrypteduserpassword
    - name: Add users
      user:
        name={{ item }}
        state=present
        password={{ encrypteduserpassword.stdout }}
      with_items:
        - "{{ username }}"
